"""criacao da tabela de tokens

Revision ID: 05356da5bf72
Revises: 23cb18077dfe
Create Date: 2026-05-04 17:54:27.404418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05356da5bf72'
down_revision: Union[str, Sequence[str], None] = '23cb18077dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expired_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expired_tokens')
    # ### end Alembic commands ###