"""adicionando unique na tabela de logout

Revision ID: 203e345e42f9
Revises: 05356da5bf72
Create Date: 2026-05-04 20:14:58.770359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203e345e42f9'
down_revision: Union[str, Sequence[str], None] = '05356da5bf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'expired_tokens', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expired_tokens', type_='unique')
    # ### end Alembic commands ###