"""ajustando o fuso horario da data como padrao

Revision ID: 7e6f668ae427
Revises: e3d8f50f9562
Create Date: 2026-04-30 15:01:01.118133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e6f668ae427'
down_revision: Union[str, Sequence[str], None] = 'e3d8f50f9562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS workout_summary;")
    
    
    op.drop_table('playing_with_neon')
    op.alter_column('exercises', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('exercises_name_key'), 'exercises', type_='unique')
    op.alter_column('sets', 'id_workout_exercise',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('sets', 'weight',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('sets', 'reps',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('workouts', 'id_user',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('workouts', 'datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('workouts_exercises', 'id_workout',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('workouts_exercises', 'id_exercise',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    
    op.execute("""
        CREATE VIEW workout_summary AS 
    SELECT users.name as user,
    exercises.name as exercise,
    workouts.datetime,
    sets.weight,
    sets.reps
    FROM sets
    JOIN workouts_exercises ON workouts_exercises.id = sets.id_workout_exercise
    JOIN exercises ON exercises.id = workouts_exercises.id_exercise
    JOIN workouts on workouts.id = workouts_exercises.id_workout
    JOIN users on users.id = workouts.id_user;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute("DROP VIEW IF EXISTS workout_summary;")
    
    op.alter_column('workouts_exercises', 'id_exercise',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts_exercises', 'id_workout',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts', 'datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('workouts', 'id_user',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('sets', 'reps',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('sets', 'weight',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('sets', 'id_workout_exercise',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('exercises_name_key'), 'exercises', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('exercises', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    
    op.execute(""" CREATE VIEW workout_summary AS 
    SELECT users.name as user,
    exercises.name as exercise,
    workouts.datetime,
    sets.weight,
    sets.reps
    FROM sets
    JOIN workouts_exercises ON workouts_exercises.id = sets.id_workout_exercise
    JOIN exercises ON exercises.id = workouts_exercises.id_exercise
    JOIN workouts on workouts.id = workouts_exercises.id_workout
    JOIN users on users.id = workouts.id_user;
    """)
    
    # ### end Alembic commands ###