"""initial

Revision ID: e3d8f50f9562
Revises: 
Create Date: 2026-04-30 12:03:29.848347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d8f50f9562'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('playing_with_neon')
    # op.alter_column('exercises', 'name',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    # op.drop_constraint(op.f('exercises_name_key'), 'exercises', type_='unique')
    # op.alter_column('sets', 'id_workout_exercise',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.BigInteger(),
    #            nullable=False)
    # op.alter_column('sets', 'weight',
    #            existing_type=sa.NUMERIC(),
    #            type_=sa.Integer(),
    #            existing_nullable=False)
    # op.alter_column('sets', 'reps',
    #            existing_type=sa.NUMERIC(),
    #            type_=sa.Integer(),
    #            existing_nullable=False)
    # op.alter_column('workouts', 'id_user',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.BigInteger(),
    #            nullable=False)
    # op.alter_column('workouts_exercises', 'id_workout',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.BigInteger(),
    #            nullable=False)
    # op.alter_column('workouts_exercises', 'id_exercise',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.BigInteger(),
    #            nullable=False)
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts_exercises', 'id_exercise',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts_exercises', 'id_workout',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts', 'id_user',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('sets', 'reps',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('sets', 'weight',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('sets', 'id_workout_exercise',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('exercises_name_key'), 'exercises', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('exercises', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###